INSERT INTO USER (USER_ID, USERNAME, FIRST_NAME, LAST_NAME, GENDER, CONTRASENA, ESTADO) VALUES (1,'ines21','ines','saavedra','Female', '12345',1);
INSERT INTO USER (USER_ID, USERNAME, FIRST_NAME, LAST_NAME, GENDER,CONTRASENA, ESTADO ) VALUES (2,'beatriz24','beatriz','sicilia','Female', '45678', 1);
INSERT INTO USER (USER_ID, USERNAME, FIRST_NAME, LAST_NAME, GENDER,CONTRASENA, ESTADO ) VALUES (3,'breton88','jorge','breton','Male', '66666', 1);

INSERT INTO PERIODO (PERIODO_CODE, USER_ID, NOMBRE_PERIODO, MES ) VALUES (1, 1, 'verano', 'Julio');

INSERT INTO GRUPO (GRUPO_CODE, PERIODO_CODE, NOMBRE_GRUPO, FOTO) VALUES (1,1,'Gastos comida', 'http://urlfoto'); 

INSERT INTO GASTO (ID_GASTO, GRUPO_CODE, CONCEPTO, IMPORTE, FECHA) VALUES (1,1,'Comida restaurante abc', 120.50, '2022-07-15');






