
DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  USER_ID int(11) NOT NULL AUTO_INCREMENT,
  USERNAME varchar(255) DEFAULT NULL,
  FIRST_NAME varchar(50) DEFAULT NULL,
  LAST_NAME varchar(50) DEFAULT NULL,
  GENDER varchar(10) DEFAULT NULL,
  CONTRASENA varchar(255) DEFAULT NULL,
  ESTADO tinyint(10) DEFAULT NULL,
  PRIMARY KEY (USER_ID)
);



